sky:
# 数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 127.0.0.1
    port: 3306
    database: sky_take_out
    username: root
    password: root
#  地图功能
  shop:
    address: 江苏省无锡市锡山区无锡学院李园三号
  baidu:
    ak: 
#oss服务器
  alioss:
    endpoint: 
    access-key-id: 
    access-key-secret: 
    bucket-name: 
#本地redis的虚拟机服务
  redis:
    host: 192.168.208.139
    port: 6379
    password: Zhlyc123.
    database: 0
#  微信小程序服务
  wechat:
    appid:
    secret: 



