sky:
# 数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 127.0.0.1
    port: 3306
    database: sky_take_out
    username: root
    password: root
#  地图功能
  shop:
    address: 江苏省无锡市锡山区无锡学院李园三号
  baidu:
    ak: nsXmU7bAd0bXgogsvCZglX9Q57rg6s9t
#oss服务器
  alioss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    access-key-id: LTAI5tFuARKQ8BddZvq3Bdx4
    access-key-secret: u8FLoatk2XznrtFOYskAHa715x8j4q
    bucket-name: web-zh183
#本地redis的虚拟机服务
  redis:
    host: 192.168.208.139
    port: 6379
    password: Zhlyc123.
    database: 0
#  微信小程序服务
  wechat:
    appid: wx4bcf9e2f64d8e76f
    secret: 45c085eff8bcfa585a1c38a1d85ffa80

#    微信支付
#    mchid: 1561414331
#    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
#    privateKeyFilePath: C:\software\apiclient_key.pem
#    apiV3Key: CZBK51236435wxpay435434323FFDuv3
#    weChatPayCertFilePat: C:\software\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
#    notifyUrl: https://7d5f5eec.r5.cpolar.top/notify/paySuccess
#    refundNotifyUrl: https://7d5f5eec.r5.cpolar.top/notify/refundSuccess
#


